### ISSUE TITLE
Uncaught TypeError: _ref.getURI is not a function

### ISSUE THREAD

**Issue by Psykofloyd** [chemoish/atom-pane-layout#13]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [pane-layout-plus](https://github.com/chemoish/atom-pane-layout) package, v0.7.3

### Stack Trace

Uncaught TypeError: _ref.getURI is not a function

```
At /Users/pollier/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:79

TypeError: _ref.getURI is not a function
    at Object.module.exports.formatLayout (/Users/pollier/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:79:59)
    at Object.module.exports.layout (/Users/pollier/.atom/packages/pane-layout-plus/lib/pane-layout.coffee:21:25)
    at atom-workspace.atom.commands.add.pane-layout:column-2 (/Users/pollier/.atom/packages/pane-layout-plus/lib/pane-layout.coffee:7:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

### Commands

```
     -0:14.5.0 pane-layout:column-3 (atom-text-editor.editor.is-focused)
     -0:10.9.0 term2:open (atom-text-editor.editor.is-focused)
     -0:00.7.0 pane-layout:column-2 (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "nucleus-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autoclose-html, v0.19.0
autocomplete-clang, v0.8.7
file-icons, v1.6.9
header-42, v0.3.0
highlight-selected, v0.10.1
linter, v1.8.1
minimap, v4.13.4
nucleus-dark-ui, v0.5.14
pane-layout-plus, v0.7.3
pigments, v0.15.0
save-session, v0.15.7
tabs-to-spaces, v0.11.1
term2, v0.9.21
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by chemoish** [comment]
Feel free to open up a pull request or more information. As I am not able to reproduce (Maybe package conflicts).

**Comment by itzaks** [comment]
Able to reproduce this when the active pane is not a file but something generated by atom. In my case a window from the browser-preview package.

**Comment by chemoish** [comment]
@itzaks, can you post basic steps / packages? That would be helpful. Thanks.

**Comment by rswerve** [comment]
Same experience as @itzaks.  If I have, for example, Settings as the active pane, and try to change the layout, I get this error.

**Comment by chemoish** [comment]
@rswerve, Ok thanks. I'll take a look.

**Comment by chemoish** [comment]
@rswerve, I just did a quick test (I am at home).

Package: 0.7.3
Atom: 1.7.2
System: Windows 10

1. Open settings `Ctrl+,`
2. Change layout `Alt+Shift+2`
3. Change pane `Ctrl+2`
4. Change pane `Ctrl+1`

I am not experiencing an error.

**Comment by rswerve** [comment]
Thanks for checking.  I tried again, and I also don't get an error in the circumstance you describe.  Where I do get the error is if I have an Atom Runner pane open and active.  Seems to have been a different package for all three people reporting the error.

**Comment by t7yang** [comment]
I get this error with git-control, when focus on git-control tab and trying to change the pane size, then you get the error.
![2016-11-16_14-25-13](https://cloud.githubusercontent.com/assets/4502661/20336899/96359386-ac08-11e6-94c6-ee9aecb28ce8.gif)

**Comment by chemoish** [comment]
Feel free to open a PR. 

If not interested, provide a couple of smaller packages where I can duplicate the issue.

I would need to then look at those plugins to see how they are generating windows and if they can be moved.

**Comment by t7yang** [comment]
@chemoish 
only need new a new profile atom with atom-pane-layout and git-control install.
do what I show, then u get the error.
