### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by despairblue** [chemoish/atom-pane-layout#8]
[Enter steps to reproduce below:]

try to use it from the settings pane

**Atom Version**: 0.183.0
**System**: linux 3.14.26-1-lts
**Thrown From**: [pane-layout-plus](https://github.com/chemoish/atom-pane-layout) package, v0.6.5

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/despairblue/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:70

TypeError: undefined is not a function
  at Object.module.exports.formatLayout (/home/despairblue/.atom/packages/pane-layout-plus/lib/pane-layout-formatter.coffee:70:59)
  at Object.module.exports.layout (/home/despairblue/.atom/packages/pane-layout-plus/lib/pane-layout.coffee:13:25)
  at atom-workspace.atom.commands.add.pane-layout:column-2 (/home/despairblue/.atom/packages/pane-layout-plus/lib/pane-layout.coffee:7:35)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -1:56.3 pane:close (atom-pane.pane)
     -0:37.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:34.8 core:confirm (atom-text-editor.editor.mini)
     -0:34.8 application:open-your-config (atom-text-editor.editor.is-focused)
     -0:04.9 tree-view:toggle (atom-text-editor.editor)
     -0:03.7 settings-view:open (atom-text-editor.editor)
     -0:02.6 pane-layout:column-2 (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "symbols-view",
      "themed-settings",
      "spell-check",
      "linter-scspell",
      "symbol-gen"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-alignment, v0.11.0
atom-color-highlight, v3.0.8
atom-jasmine, v0.5.0
atom-ternjs, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
autocomplete-snippets, v1.0.1
block-travel, v1.0.2
bug-report, v0.6.2
color-picker, v1.4.4
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v0.3.0
file-icons, v1.4.11
filetype-color, v0.1.4
git-log, v0.3.0
go-plus, v3.2.2
grammar-token-limit, v0.1.1
highlight-selected, v0.9.0
indentation-indicator, v0.4.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.8
language-dockerfile, v0.1.0
language-haskell, v1.0.0
language-latex, v0.4.1
language-nimrod, v0.1.0
language-puppet, v0.10.0
language-tss, v0.0.1
latex, v0.18.1
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-eslint, v0.4.1
linter-jshint, v0.1.0
linter-puppet-lint, v0.2.8
minimap, v4.3.1
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v4.0.0
minimap-git-diff, v4.0.0
minimap-highlight-selected, v4.1.0
open-last-project, v0.3.4
package-cop, v0.2.2
pane-layout-plus, v0.6.5
project-manager, v1.15.5
regex-railroad-diagram, v0.7.1
tab-smart-sort, v0.1.2
tabs-to-spaces, v0.8.1
test-status, v0.27.1
zentabs, v0.8.2

# Dev
atom-ternjs, v0.4.17
autocomplete-plus, v2.0.2
```

**Comment by chemoish** [comment]
Thanks for the issue. It looks like it has to do with a bug in atom panes.

```
atom.workspace.getActivePaneItem().getUri()

file       => returns file path
settings   => returns undefined error because method doesn't exist
empty file => returns empty string
```

Pane::getUri is deprecated but doesn't get fired by deprecation cop.

**Comment by chemoish** [comment]
https://github.com/atom/settings-view/commit/c70ee5ac82228fc9019cbc3c1bcdb92c7af13a28

**Comment by chemoish** [comment]
Fixed by https://github.com/chemoish/atom-pane-layout/commit/a80a881343d7cdbff342618b0711f8c84fd0ee11
